---
title: "lm_fit"
author: "Claire"
date: "12/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggfortify)
```


# Reading data for Lux and Belgium
```{r}
library(rio)
LUX_original <- import("data/LUX_n.xlsx")
BLG_original <- read_csv("data/BLG.csv")
LUX <- LUX_original %>% 
  filter(new_cases>0)
BLG <- BLG_original %>% 
  filter(new_cases>0)
```
```{r}
glimpse(LUX)
```
```{r}
glimpse(BLG)

```

# Covid cases distribution with time
```{r}
LUX %>% ggplot( aes(date, as.numeric(new_cases))) +
 geom_col(fill = "blue", alpha = 0.6) + 
 theme_minimal(base_size = 14) +
  labs(title = "Weekly COVID-19 Cases in Luxembourg", x= "Date", y= "Daily confirmed cases") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```
```{r}
BLG %>% ggplot( aes(date, as.numeric(new_cases))) +
 geom_col(fill = "blue", alpha = 0.6) + 
 theme_minimal(base_size = 14) +
  labs(title = "Weekly COVID-19 Cases in Belgium", x= "Date", y= "Daily confirmed cases") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```

# Weekly confirmed new cases per capita calculation (cpc)

```{r}
lux_population = 626108
blg_population = 11522440

LUX$cpc <- 10000*LUX$new_cases/lux_population
BLG$cpc <- 10000*BLG$new_cases/blg_population
```

# start and end dates for the calculations
```{r}
start_date = as.Date("2020-7-1")
s_date = as.Date("2020-3-1")
end_date = as.Date("2021-12-15")
```

#  Weekly confirmed new cases per capita with tempreture 

```{r}
LUX %>% 
  filter(date<end_date & date>start_date) %>% 
  filter(weekly_temp>-5) %>% 
  ggplot(aes(date, cpc)) +
  geom_col() +
  geom_point(aes(y = weekly_temp/0.5), color = "red") +
  scale_y_continuous("Daily confirmed new cases per capita", sec.axis = sec_axis( ~.*0.5, name = "Temperature")) +
  ggtitle("Luxembourg") 
```

```{r}
BLG %>% 
  filter(date<end_date & date>s_date) %>% 
  filter(weekly_temp>0) %>% 
ggplot(  aes(date, cpc)) +
  geom_col() +
  geom_point(aes(y = weekly_temp/0.5), color = "red") +
  scale_y_continuous("Weekly confirmed new cases per capita ", sec.axis = sec_axis( ~.*0.5, name = "Temperature")) +
  ggtitle("Belgium") 
```
# Weely confirmed new cases pc vs tempreture

```{r}
LUX$logC <- log(LUX$new_cases)
BLG$logC <- log(BLG$new_cases)

mean(LUX$logC)
mean(BLG$logC)
LUX %>% 
  filter(date<end_date & date>start_date) %>%
  filter(weekly_temp>0) %>% 
  ggplot(aes(weekly_temp, logC))+
  geom_point()
  
```
```{r}
BLG %>% 
  filter(date<end_date & date>start_date) %>%
  filter(weekly_temp>0) %>% # 3 outliers
  ggplot(aes(weekly_temp, logC))+
  geom_point()
  
```

# Linear Model fit
```{r}
LUX_fit <- LUX %>% 
  filter(date<end_date & date>start_date) %>%
  filter(weekly_temp>0) %>% 
  lm(logC ~ weekly_temp, data = .) 

summary(LUX_fit)
confint(LUX_fit)

LUX_C <- LUX %>% 
  filter(date<end_date & date>start_date)
cor(LUX_C$weekly_temp, LUX_C$logC)
cov(LUX_C$weekly_temp, LUX_C$logC)
```

```{r}
BLG_fit <- BLG %>% 
  filter(date<end_date & date>s_date) %>%
  filter(weekly_temp>0) %>% 
  lm(logC ~ weekly_temp, data = .) 

summary(BLG_fit)
confint(BLG_fit)

BLG_C <- BLG %>% 
  filter(date<end_date & date>s_date)
cor(BLG_C$weekly_temp, BLG_C$logC)
cov(BLG_C$weekly_temp, BLG_C$logC)
```

```{r}
autoplot(LUX_fit)
```

```{r}
autoplot(BLG_fit)
```
```{r}
LUX %>% 
  filter(date<end_date & date>start_date) %>%
  filter(weekly_temp>0 ,new_cases>0) %>% 
  ggplot(aes(weekly_temp, logC))+
  geom_point()+
    geom_abline(slope = coef(LUX_fit)[2], intercept = coef(LUX_fit)[1],linetype=2, color= "blue")+
    geom_hline(yintercept = mean(LUX$logC), color = "darkgreen") +
    geom_vline(xintercept = mean(LUX$weekly_temp), color = "darkgreen")+
  stat_smooth(method = lm,)+
  xlim(0, 40)+
  ggtitle("Luxembourg")
```

```{r}
BLG %>% 
  filter(date<end_date & date>s_date) %>%
  filter(weekly_temp>0 ,new_cases>0) %>% 
  ggplot(aes(weekly_temp, logC))+
  geom_point()+
    geom_abline(slope = coef(BLG_fit)[2], intercept = coef(BLG_fit)[1],linetype=2, color= "blue")+
    geom_hline(yintercept = mean(BLG$logC ), color = "darkgreen") +
    geom_vline(xintercept = mean(BLG$weekly_temp), color = "darkgreen")+
  stat_smooth(method = lm,)+
  xlim(0, 40)+
  ggtitle("Belgium")
```
```{r}

library(broom)
BLG_temp_case <- BLG %>% 
  filter(date<end_date & date>s_date) %>%
  filter(weekly_temp>0 ,new_cases>0) %>% 
  mutate(expected = augment(BLG_fit)$.fitted) %>% 
  mutate(residual = log(new_cases)-expected) 

hist(BLG_temp_case$residual)
```
```{r}
library(broom)
LUX_temp_case <- LUX %>% 
  filter(date<end_date & date>start_date) %>%
  filter(weekly_temp>0 ,new_cases>0) %>% 
  mutate(expected = augment(LUX_fit)$.fitted) %>% 
  mutate(residual = log(new_cases)-expected) 

hist(LUX_temp_case$residual)

```
```{r}
new.dat <- data.frame(weekly_temp=35)
predict(BLG_fit, newdata = new.dat, interval = 'confidence')
```
```{r}

new.dat <- data.frame(weekly_temp=35)
predict(LUX_fit, newdata = new.dat, interval = 'confidence')

```

